apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxhttps
        image: us.gcr.io/adroit-lantern-308821/nginx:v1
        ports:
        - containerPort: 443
        - containerPort: 80
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet